name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Set Git to support long paths
      - name: Set Git to support long paths
        run: git config --global core.longpaths true

      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install Visual Studio Build Tools
      - name: Install Visual Studio Build Tools
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.ManagedDesktop --add Microsoft.VisualStudio.Workload.WebDevelopment"

      # Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Adjust .NET version if needed

      # Restore Dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # Build Project
      - name: Build Project
        run: dotnet build --no-restore

      # Run Tests
      - name: Run Tests
        run: dotnet test --no-build --verbosity normal
