name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Set Git to support long paths
      - name: Set Git to support long paths
        run: git config --global core.longpaths true

      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install Visual Studio Build Tools 2019 with Web Development
      - name: Install Visual Studio Build Tools
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.ManagedDesktop --add Microsoft.VisualStudio.Workload.WebDevelopment --add Microsoft.VisualStudio.Component.Windows10SDK.18362 --includeRecommended"

      # Setup .NET SDK (for compatibility, we keep the latest SDK but target 4.8.1)
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restore Dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # Build Project
      - name: Build Project
        run: dotnet build --no-restore /p:TargetFramework=net48

      # Run Tests
      - name: Run Tests
        run: dotnet test --no-build --verbosity normal /p:TargetFramework=net48
