name: ASP.NET MVC CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Enable long path support
      run: |
        reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer" /v LongPathsEnabled /t REG_DWORD /d 1 /f

    - name: Enable Git Long Path Support
      run: |
        git config --global core.longpaths true

    - name: Set up .NET Framework 4.8.1
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: 'latest'

    - name: Restore NuGet packages
      run: |
        nuget restore Order_Processing_Assignment.sln

    - name: Build the solution
      run: |
        msbuild Order_Processing_Assignment.sln /p:Configuration=Release

    - name: Run Tests (optional)
      run: |
        vstest.console Order_Processing_Assignment.dll --logger:trx

    - name: Publish Artifacts (optional)
      run: |
        mkdir -p $(Build.ArtifactStagingDirectory)
        copy /y "path\to\your\build\output\*" $(Build.ArtifactStagingDirectory)
