name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set Git longpaths
      run: git config --system core.longpaths true

    - name: Enable Long Path Support
      run: |
        Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '4.8.x'

    - name: Install NuGet
      run: nuget restore

    - name: Build project
      run: msbuild /p:Configuration=Release

    - name: Run tests
      run: |
        $solution = (Get-ChildItem -Filter *.sln).FullName
        vstest.console.exe $solution /logger:trx
