name: Build and Test MyMvcApplication

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Configure Git for long paths
        run: git config --global core.longpaths true

      - uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2
        with:
          nuget-version: 'latest'

      - name: Restore NuGet packages
        run: nuget restore Order_Processing_Assignment.sln

      - name: Build Main Project
        run: msbuild Order_Processing_Assignment.sln /p:Configuration=Release

      - name: Build Test Project
        run: msbuild UnitTestProject1/UnitTestProject1.csproj /p:Configuration=Release

      - name: Test  # Run the tests using dotnet test
        run: dotnet test UnitTestProject1/UnitTestProject1.csproj --configuration Release

      - name: Publish
        run: msbuild Order_Processing_Assignment.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish
          path: ./publish
