name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Set Git to support long paths
      - name: Set Git to support long paths
        run: git config --global core.longpaths true

      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install Visual Studio Build Tools 2019 with Web Development
      - name: Install Visual Studio Build Tools
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.ManagedDesktop --add Microsoft.VisualStudio.Workload.WebDevelopment --add Microsoft.VisualStudio.Component.Windows10SDK.18362 --includeRecommended"

      # Setup .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restore Dependencies
      - name: Restore Dependencies
        run: nuget restore Order_Processing_Assignment.sln

      # Build Project using MSBuild
      - name: Build Project
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe" /p:Configuration=Release Order_Processing_Assignment.sln

      # Run Tests using VSTest.console.exe
      - name: Run Tests
        run: |
          $testAssemblies = Get-ChildItem -Recurse -Filter *Test*.dll -Path '.\bin\Release'
          foreach ($testAssembly in $testAssemblies) {
            "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" $testAssembly.FullName
          }
