name: Build and Test ASP.NET MVC Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable long path support
      run: |
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\FileSystem" /v LongPathsEnabled /t REG_DWORD /d 1 /f
        echo "Long path support enabled"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Move repo to shorter path
      run: |
        mkdir C:\shortrepo
        move D:\a\_temp\* C:\shortrepo
        cd C:\shortrepo

    - name: Install .NET Framework 4.8.1
      run: |
        choco install dotnet-4.8.1-sdk --version 4.8.1

    - name: Restore dependencies
      run: nuget restore ./Order_Processing_Assignment.sln

    - name: Build the project
      run: msbuild ./Order_Processing_Assignment.sln /p:Configuration=Release

    - name: Run tests
      run: vstest.console ./UnitTestProject1/bin/Debug/Order_Processing_Assignment.dll

    - name: Publish build artifacts
      if: success()
      run: |
        mkdir $(Build.ArtifactStagingDirectory)
        copy ./path/to/your/output/* $(Build.ArtifactStagingDirectory)
