name: Build and Deploy ASP.NET MVC 4.8.1 Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Framework
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: 'latest'

    - name: Restore NuGet packages
      run: nuget restore Order_Processing_Assignment.sln

    - name: Build the application
      run: msbuild Order_Processing_Assignment.sln /p:Configuration=Release

    - name: Run tests (optional)
      run: |
        vstest.console.exe UnitTestProject1.dll

    - name: Publish the application (optional)
      run: msbuild YourProject.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
